In [1]:
#CARREGANDO AS BIBLIOTECAS
import pandas as pd

In [2]:
#CARREGANDO OS DADOS EM CSV
arquivo = pd.read_csv('csv/datasets.csv')

In [3]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [4]:
#ARMAZENANDO DENTRO DE UMA VARIAVEL, E DEPOIS SUBSTITUI O RED POR 0
arquivo['style'] = arquivo['style'].replace('red', 0)

In [5]:
#ARMAZENANDO DENTRO DE UMA VARIAVEL, E DEPOIS SUBSTITUI O WHITE POR 1
arquivo['style'] = arquivo['style'].replace('white', 1)

In [6]:
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [10]:
arquivo.shape

(6497, 13)

In [7]:
#SEPARADO AS VARIAVEIS ENTRE PREDITORIAS E VARIAVEL ALVO
y = arquivo['style']
x = arquivo.drop('style', axis = 1)

In [11]:
x.shape

(6497, 12)

In [12]:
y.shape

(6497,)

In [8]:
y

0       0
1       0
2       0
3       0
4       0
       ..
6492    1
6493    1
6494    1
6495    1
6496    1
Name: style, Length: 6497, dtype: int64

In [9]:
x

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [14]:
from sklearn.model_selection import train_test_split

#CRIANDO OS CONJUNTOS DE DADOS DE TREINOS E TESTE:
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [15]:
x_treino.shape

(4547, 12)

In [16]:
y_treino.shape

(4547,)

In [17]:
x_teste.shape

(1950, 12)

In [18]:
y_teste.shape

(1950,)

In [20]:
from sklearn.ensemble import ExtraTreesClassifier
#CRIAÇÃO DO MODELO:
modelo = ExtraTreesClassifier(n_estimators=100)
modelo.fit(x_treino, y_treino)

#IMPRIMMINDO RESULTADOS:
resultado = modelo.score(x_teste, y_teste)
print('Acurácia: ', resultado)

Acurácia:  0.9974358974358974

In [21]:
y_teste[400:403]

5491    1
4817    1
4663    1
Name: style, dtype: int64

In [22]:
x_teste[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
5491,6.0,0.21,0.30,8.7,0.036,47.0,127.0,0.99368,3.18,0.39,10.6,5
4817,6.5,0.29,0.25,2.5,0.142,8.0,111.0,0.99270,3.00,0.44,9.9,4
4663,7.4,0.21,0.80,12.3,0.038,77.0,183.0,0.99778,2.95,0.48,9.0,5

In [23]:
previsoes = modelo.predict(x_teste[400:403])

In [24]:
previsoes

array([1, 1, 1])